Dropzone image upload demo
CottaCush/yii2-base-project pull request #12
Opened 2017-08-29 15:49 UTC by yemexx1

Add demo for Dropzone Image Upload Widget and Yii2 Object Storage component

2017-08-30 12:04 UTC, kenny-wealth commented
Please resolve conflicts

2017-09-06 15:52 UTC, olajideoye commented on composer.json
> +        "cottacush/yii2-utils": "dev-features/file-upload-service",
@yemexx1  The composer versions here should be reverted to stable versions

2017-09-06 15:55 UTC, olajideoye requested changes
The versions for some of our composer dependencies need to be reverted back to stable versions.

2017-09-06 15:55 UTC, olajideoye commented on composer.json
> +        "cottacush/yii2-widgets": "dev-master",
@yemexx1 The composer versions here should be reverted to stable versions

2019-05-13 12:59 UTC, closed without merging